### ISSUE TITLE
Folder names start with upper-case letter

### ISSUE THREAD

**Issue by 7u1ian** [CATYNX-blue-ocean/HR-NYC-ATX#4]
Examples:

/Client
/Database
/Server

Let's change it to lower case. It's weird.

Things that should be lower-case: 
Files where a class lives (classes by convention should start upper-case), but since most of us will use functional components that's fine too. Examples:
App.jsx
LandingPage.jsx

@nickknowles1 @camboucher @thejasondye

**Comment by nickknowles1** [comment]
Easy fix

**Comment by 7u1ian** [comment]
> Easy fix
> […](#)
> Sent from my iPhone
> On Aug 28, 2021, at 10:41 PM, 7u1ian ***@***.***> wrote: ﻿ Examples: /Client /Database /Server Let's change it to lower case. It's weird. Things that should be lower-case: Files where a class lives (classes by convention should start upper-case), but since most of us will use functional components that's fine too. Examples: App.jsx LandingPage.jsx @nickknowles1 @camboucher @thejasondye — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Yes I fixed it in my changes, but I wanted to talk about it with you three.

**Comment by thejasondye** [comment]
Definitely lowercase.  The convention is "folder_name" for what we've seen so far, so let's follow that.

Definitely uppercase file names and functional components for the components.  And we should all be using hooks at this point I think?  Especially with Zustand. Either way, both should be upper case.

**Comment by 7u1ian** [comment]
I don't know how to fix this. Git doesn't push a folder rename if its only difference is upper vs lower case. Here's how to do it locally https://www.w3docs.com/snippets/git/how-to-properly-rename-a-directory-in-a-git-repository.html

good news is import statements don't care if a path is upper or lower case. It's not a big deal though. Closing
